[project]
name = "maiz-yield-prediction"
version = "0.1.0"
description = ""
authors = [
    {name = "Santiago Scozziero",email = "santiagohernanscozziero@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
]

[tool.poetry]
packages = [{include = "maiz_yield_prediction", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
